// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8gLSQrbvFo0I5v9QY97mTdDpbWOcn8ZU',
    appId: '1:1087435709574:web:695005976de9291d51c507',
    messagingSenderId: '1087435709574',
    projectId: 'pokedex-e9f8b',
    authDomain: 'pokedex-e9f8b.firebaseapp.com',
    storageBucket: 'pokedex-e9f8b.appspot.com',
    measurementId: 'G-WMFKWDQXZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq-XSv74IGoXIcCEjpnkzTp3Wv9PaDZkM',
    appId: '1:1087435709574:android:9c66cbf530c82de151c507',
    messagingSenderId: '1087435709574',
    projectId: 'pokedex-e9f8b',
    storageBucket: 'pokedex-e9f8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvJeNy5u_NFejb95NQdPYQmdp1X1wKbrI',
    appId: '1:1087435709574:ios:d3f5cb16b853810451c507',
    messagingSenderId: '1087435709574',
    projectId: 'pokedex-e9f8b',
    storageBucket: 'pokedex-e9f8b.appspot.com',
    iosClientId: '1087435709574-8g0fpefq3jbjdoclgdfkhdk5u5a75rgi.apps.googleusercontent.com',
    iosBundleId: 'dev.duocore.pokedex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvJeNy5u_NFejb95NQdPYQmdp1X1wKbrI',
    appId: '1:1087435709574:ios:d3f5cb16b853810451c507',
    messagingSenderId: '1087435709574',
    projectId: 'pokedex-e9f8b',
    storageBucket: 'pokedex-e9f8b.appspot.com',
    iosClientId: '1087435709574-8g0fpefq3jbjdoclgdfkhdk5u5a75rgi.apps.googleusercontent.com',
    iosBundleId: 'dev.duocore.pokedex',
  );
}
